apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.name }}-ingress"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certificate.environment }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: domain-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.name }}-node-port"
                port:
                  number: {{  .Values.service.port}}