name: react-xr-workshop
namespace: react-xr-workshop-dev

certificate:
  environment: dev

image:
  repository: paloitinternalregistry.azurecr.io/react-xr-workshop
  pullPolicy: Always
  
service:
  type: NodePort
  port: 80
  targetPort: 80

ingress:
  host: react-xr-workshop-dev.palo-it.app
