name: Build and deploy App on AKS

on:
 push:
   branches:
     - main

jobs:
 build-and-deploy:
   uses: palo-it-th/reusable-workflows/.github/workflows/internal-cluster-ci-cd.yml@main
   with:
     image-name: paloitinternalregistry.azurecr.io/${{ github.repository }}:${{ github.ref_name }}
     resource-group-name: palo-it-cluster-rg
     cluster-name: palo-it-internal-cluster
     helm-chart-path: ./demo-app/infrastructure/helm
     docker-file-path: ./demo-app/Dockerfile
     namespace: ${{ github.repository }}-dev
   secrets:
     container-registry-server: ${{ secrets.ACR_INTERNAL_CLUSTER_LOGIN_SERVER }}
     container-registry-admin-username: ${{ secrets.ACR_INTERNAL_CLUSTER_ADMIN_USERNAME }}
     container-registry-admin-password: ${{ secrets.ACR_INTERNAL_CLUSTER_ADMIN_PASSWORD }}
     azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
     azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}